# 1. Numpy

 * __Numpy provides efficient storage.__
 * __Numpy provides better ways of handling data for processing.__
 * __It is fast.__
 * __it is easy to learn.__
 * __Numpy user relatively less memory to store data.__

# Jupyter

 * __The Jupyter Notebook is an open source web application that allows you to create line code, equations, visualizations and narrative text.__
 * __The Notebook has support for over 40 Programming languages, including Python, R, Jullia and Scala.__
 * __Notebooks can be shared with other using email,Dropbox,GitHub and the Jupyter Notebook viewers.__
 * __Your Code can produce rich, interactive output HTML, images, vides, LaTeX, and Many custom types.__

In [1]:
import numpy as np

In [2]:
list=[2,3,32,7]
list

[2, 3, 32, 7]

In [3]:
type(list)

list

In [4]:
myarray=np.array(list)
myarray

array([ 2,  3, 32,  7])

In [5]:
myarray=np.array([2,3,32,7],np.int8)
myarray

array([ 2,  3, 32,  7], dtype=int8)

In [6]:
# 1-D array

myarr=np.array([3,6,37,8],np.int64)
myarr

array([ 3,  6, 37,  8], dtype=int64)

In [7]:
# 2-D array
myarr=np.array([[3,6,9,12]],np.int64)
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [8]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [9]:
# finding value with index number

print(myarr[0,0])
print(myarr[0,1])
print(myarr[0,2])
print(myarr[0,3])
print(myarr[0,4])

3
6
9
12


IndexError: index 4 is out of bounds for axis 1 with size 4

In [10]:
print(myarr[1,3])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [11]:
# show the details of array

myarr.shape

(1, 4)

In [12]:
myarray.dtype

dtype('int8')

In [13]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [14]:
# how to change element in the numpy array

myarr[0,0]=45  #90,50,55
myarr

array([[45,  6,  9, 12]], dtype=int64)

# Note:
 * __There are 5 general mechanism for creating array:__
    * __1. Conversion from other Python structure.(eg:list,tuples)__
    * __2. Instrinsic numpy array Creating object(eg: arange, one, Zeros etc.)__
    * __3. Reading arrays from disk, either from standard or custom formats.__
    * __4. Creating arrays from raw bytes through the use of string of buffers.__
    * __5. Use of special library function eg(random).__

In [15]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [16]:
# Checking the data type of the array

listarray.dtype

dtype('int32')

In [17]:
# Checking the shape of the array.
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [19]:
# Set array  # Data type object

np.array({34,25,36,88,99},dtype=object)


array({34, 99, 36, 88, 25}, dtype=object)

In [20]:
zero=np.zeros((3,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zero.dtype

dtype('float64')

In [22]:
range=np.arange(15)

In [23]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.linspace(50,50.05,num=100)


array([50.        , 50.00050505, 50.0010101 , 50.00151515, 50.0020202 ,
       50.00252525, 50.0030303 , 50.00353535, 50.0040404 , 50.00454545,
       50.00505051, 50.00555556, 50.00606061, 50.00656566, 50.00707071,
       50.00757576, 50.00808081, 50.00858586, 50.00909091, 50.00959596,
       50.01010101, 50.01060606, 50.01111111, 50.01161616, 50.01212121,
       50.01262626, 50.01313131, 50.01363636, 50.01414141, 50.01464646,
       50.01515152, 50.01565657, 50.01616162, 50.01666667, 50.01717172,
       50.01767677, 50.01818182, 50.01868687, 50.01919192, 50.01969697,
       50.02020202, 50.02070707, 50.02121212, 50.02171717, 50.02222222,
       50.02272727, 50.02323232, 50.02373737, 50.02424242, 50.02474747,
       50.02525253, 50.02575758, 50.02626263, 50.02676768, 50.02727273,
       50.02777778, 50.02828283, 50.02878788, 50.02929293, 50.02979798,
       50.03030303, 50.03080808, 50.03131313, 50.03181818, 50.03232323,
       50.03282828, 50.03333333, 50.03383838, 50.03434343, 50.03

In [25]:
np.linspace(2.0,3.0,num=100, endpoint=False)

array([2.  , 2.01, 2.02, 2.03, 2.04, 2.05, 2.06, 2.07, 2.08, 2.09, 2.1 ,
       2.11, 2.12, 2.13, 2.14, 2.15, 2.16, 2.17, 2.18, 2.19, 2.2 , 2.21,
       2.22, 2.23, 2.24, 2.25, 2.26, 2.27, 2.28, 2.29, 2.3 , 2.31, 2.32,
       2.33, 2.34, 2.35, 2.36, 2.37, 2.38, 2.39, 2.4 , 2.41, 2.42, 2.43,
       2.44, 2.45, 2.46, 2.47, 2.48, 2.49, 2.5 , 2.51, 2.52, 2.53, 2.54,
       2.55, 2.56, 2.57, 2.58, 2.59, 2.6 , 2.61, 2.62, 2.63, 2.64, 2.65,
       2.66, 2.67, 2.68, 2.69, 2.7 , 2.71, 2.72, 2.73, 2.74, 2.75, 2.76,
       2.77, 2.78, 2.79, 2.8 , 2.81, 2.82, 2.83, 2.84, 2.85, 2.86, 2.87,
       2.88, 2.89, 2.9 , 2.91, 2.92, 2.93, 2.94, 2.95, 2.96, 2.97, 2.98,
       2.99])

In [26]:
# empty array

emp=np.empty((4,6))
emp

array([[9.02582318e-312, 7.70742408e-322, 0.00000000e+000,
        0.00000000e+000, 8.01097888e-307, 1.15998412e-028],
       [4.31603868e-080, 1.94919985e-153, 1.35717430e+131,
        7.06652016e-096, 7.06652016e-096, 1.81148490e-152],
       [9.37041222e-076, 6.98345624e-077, 6.98345624e-077,
        6.01391519e-154, 7.06673073e-096, 7.06652016e-096],
       [7.18988929e+140, 4.99874708e+217, 4.47303447e-143,
        1.46899974e+179, 9.08367237e+223, 1.16466228e-028]])

In [27]:
# matrix

b=np.empty(10,dtype=int)
b

array([      0,       1,       0, 5570652,    1120,       0,     768,
             0, 7209065, 6619136])

In [28]:
print(b)

[      0       1       0 5570652    1120       0     768       0 7209065
 6619136]


In [29]:
# identity

ide=np.identity(1000)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
# arange

arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr.shape

(99,)

In [33]:
arr.dtype

dtype('int32')

In [34]:
# numpy array
x=[[1,2,3],[4,5,6],[7,8,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 0]]

In [35]:
x.shape

AttributeError: 'list' object has no attribute 'shape'

In [36]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [37]:
ar.shape

(3, 3)

In [38]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [39]:
ar.sum(axis=0)

array([12, 15,  9])

In [40]:
ar.sum(axis=1)

array([ 6, 15, 15])

In [41]:
a= np.array([1,2,3])
b=a+2
print(b)

[3 4 5]


In [42]:
c=np.array([2,4,6])
d=a+c
print(d)

[3 6 9]


In [43]:
a

array([1, 2, 3])

In [44]:
a1=3*a
a1

array([3, 6, 9])

In [45]:
a

array([1, 2, 3])

In [46]:
a2=a/2
a2

array([0.5, 1. , 1.5])

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [48]:
c3=ar/2
c3

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 0. ]])

In [49]:
a,b

(array([1, 2, 3]), array([3, 4, 5]))

In [50]:
c4=a*b
c4

array([ 3,  8, 15])

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [52]:
ar.shape

(3, 3)

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

# Transpose()

 * __With the help of Numpy numpy.transpose(), we can perofrm the simple function of transpose within one line using numpy.transpose() method of numpy. It can transpose the 2-D array on the other hand it has no effect on 1-D arrays. This method transpose the 2-D arrays.__

In [54]:

ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 0]])

In [14]:
x=np.array([[10,20,30],[40,50,60],[70,80,100],[110,120,140]])
x

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80, 100],
       [110, 120, 140]])

In [ ]:
# sum sub, multiply,divition, shape, size, dtype, Transpose

In [57]:
x

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80, 100],
       [110, 120, 140]])

In [58]:
x.T

array([[ 10,  40,  70, 110],
       [ 20,  50,  80, 120],
       [ 30,  60, 100, 140]])

In [69]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [72]:
ar.flat

In [74]:
x.ravel()

array([ 10,  20,  30,  40,  50,  60,  70,  80, 100, 110, 120, 140])

In [75]:
for items in ar.flat:
    print(items)

1
2
3
4
5
6
7
8
0


In [76]:
x.ndim

2

In [77]:
ar.nbytes

36

In [78]:
x.nbytes

48

In [79]:
one=np.array([1,2,3,4,5,6,78,98])
one.size

8

In [80]:
one1=[1,2,3,4,5,6,78,98]
one1      

[1, 2, 3, 4, 5, 6, 78, 98]

 * __The main difference between attributes and method is that attributes are data, while method are action.__
 * __This means that attributes store information, while method performs actions.__
 * __For Example: An attribute might store the name of the array, while method might be a function that calculates the sum of the elements of an array. To call an attributes, You can use the same dot notation and add parentheses, like this:__
 * __array.attributes*__
 * __array.method(argument1,arguments2)__

In [92]:
x1=np.array([1,2000,3,4,5,6,634,0])
x1

array([   1, 2000,    3,    4,    5,    6,  634,    0])

In [93]:
x1.argmax()

1

In [94]:
x1.argmin()

7

In [95]:
x1.argsort()

array([7, 0, 2, 3, 4, 5, 6, 1], dtype=int64)

In [96]:
x1.sort()

In [97]:
x1

array([   0,    1,    3,    4,    5,    6,  634, 2000])

In [101]:
print(x1.max())

2000


In [102]:
print(x1.min())

0


In [15]:
ar=np.array([[10,20,14000],[40,50,60],[70,80,100],[110,120,140]])
ar

array([[   10,    20, 14000],
       [   40,    50,    60],
       [   70,    80,   100],
       [  110,   120,   140]])

In [107]:
ar.argmax(axis=0)

array([3, 3, 0], dtype=int64)

In [108]:
ar.argmax(axis=1)

array([2, 2, 2, 2], dtype=int64)

In [2]:
x=np.array([75,72,68,65,67,73])
x

array([75, 72, 68, 65, 67, 73])

In [13]:
np.mean(x)

70.0

In [4]:
np.average(x)

70.0

In [12]:
np.std(x)

3.559026084010437

In [16]:
ar

array([[   10,    20, 14000],
       [   40,    50,    60],
       [   70,    80,   100],
       [  110,   120,   140]])

In [17]:
np.std(ar)

3849.4833708203264

In [18]:
x

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80, 100],
       [110, 120, 140]])

In [19]:
np.std(x)

39.8869931459144

# Slicing numpy array

In [4]:
mx=np.arange(1,101)
mx

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
mx=np.arange(1,101).reshape(10,10)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [6]:
mx=np.arange(1,101).reshape(5,20)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [7]:
mx=np.arange(1,101).reshape(10,10)
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [16]:
x=mx[0,0]
x

1

In [17]:
x.ndim

0

In [22]:
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
mx[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
mx[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [38]:
mx[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [34]:
mx[:,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44],
       [53, 54],
       [63, 64],
       [73, 74],
       [83, 84],
       [93, 94]])

In [36]:
mx[:,0:1].ndim

2

In [39]:
mx[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

# Concatenation of an array

In [3]:
arr1=np.arange(1,17).reshape(4,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
arr2=np.arange(17,33).reshape(4,4)
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [5]:
# creating a list

list1=[2,4,6,7]
list2=[1,8,3,5]

In [6]:
list1+list2

[2, 4, 6, 7, 1, 8, 3, 5]

In [7]:
arr1+arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [11]:
# concatenate() function
x=np.concatenate((arr1,arr2))
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [9]:
# concatenate() function
x=np.concatenate((arr1,arr2),axis=1)
x

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [12]:
# horizontal concatenate

arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
arr2

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [15]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [17]:
x1=np.hstack((arr1,arr2))
x1

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [18]:
x1

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [22]:
x2= np.hstack((arr1,arr2,x1))
x2

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16, 29, 30, 31, 32]])

In [30]:
x=arr1
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
type(x)

numpy.ndarray

# split

In [28]:
x3=np.split(arr1,2)
x3

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [29]:
type(x3)

list

In [32]:
x3[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
x3[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
type(x3[0])

numpy.ndarray

In [35]:
type(x3[1])

numpy.ndarray

In [37]:
s4=np.split(arr1,2,axis=1)
s4

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [38]:
s4[1]

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [52]:
s4[1][0,0]=20
s4

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[20,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [46]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
arr1[0,0]

1

In [57]:
s4[0][3,1]=100
s4

[array([[  1,   2],
        [  5,   6],
        [  9,  10],
        [ 13, 100]]),
 array([[20,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]