# 1. Numpy

 * __Numpy provides efficient storage.__
 * __Numpy provides better ways of handling data for processing.__
 * __It is fast.__
 * __it is easy to learn.__
 * __Numpy user relatively less memory to store data.__

# Jupyter

 * __The Jupyter Notebook is an open source web application that allows you to create line code, equations, visualizations and narrative text.__
 * __The Notebook has support for over 40 Programming languages, including Python, R, Jullia and Scala.__
 * __Notebooks can be shared with other using email,Dropbox,GitHub and the Jupyter Notebook viewers.__
 * __Your Code can produce rich, interactive output HTML, images, vides, LaTeX, and Many custom types.__

In [2]:
import numpy as np

In [2]:
list=[2,3,32,7]
list

[2, 3, 32, 7]

In [3]:
type(list)

list

In [4]:
myarray=np.array(list)
myarray

array([ 2,  3, 32,  7])

In [11]:
myarray=np.array([2,3,32,7],np.int8)
myarray

array([ 2,  3, 32,  7], dtype=int8)

In [9]:
# 1-D array

myarr=np.array([3,6,37,8],np.int64)
myarr

array([ 3,  6, 37,  8], dtype=int64)

In [13]:
# 2-D array
myarr=np.array([[3,6,9,12]],np.int64)
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [14]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [19]:
# finding value with index number

print(myarr[0,0])
print(myarr[0,1])
print(myarr[0,2])
print(myarr[0,3])
print(myarr[0,4])

3
6
9
12


IndexError: index 4 is out of bounds for axis 1 with size 4

In [20]:
print(myarr[1,3])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [21]:
# show the details of array

myarr.shape

(1, 4)

In [22]:
myarray.dtype

dtype('int8')

In [23]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [31]:
# how to change element in the numpy array

myarr[0,0]=45  #90,50,55
myarr

array([[45,  6,  9, 12]], dtype=int64)