# 1. Numpy

 * __Numpy provides efficient storage.__
 * __Numpy provides better ways of handling data for processing.__
 * __It is fast.__
 * __it is easy to learn.__
 * __Numpy user relatively less memory to store data.__

# Jupyter

 * __The Jupyter Notebook is an open source web application that allows you to create line code, equations, visualizations and narrative text.__
 * __The Notebook has support for over 40 Programming languages, including Python, R, Jullia and Scala.__
 * __Notebooks can be shared with other using email,Dropbox,GitHub and the Jupyter Notebook viewers.__
 * __Your Code can produce rich, interactive output HTML, images, vides, LaTeX, and Many custom types.__

In [1]:
import numpy as np

In [2]:
list=[2,3,32,7]
list

[2, 3, 32, 7]

In [3]:
type(list)

list

In [4]:
myarray=np.array(list)
myarray

array([ 2,  3, 32,  7])

In [5]:
myarray=np.array([2,3,32,7],np.int8)
myarray

array([ 2,  3, 32,  7], dtype=int8)

In [6]:
# 1-D array

myarr=np.array([3,6,37,8],np.int64)
myarr

array([ 3,  6, 37,  8], dtype=int64)

In [7]:
# 2-D array
myarr=np.array([[3,6,9,12]],np.int64)
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [8]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [9]:
# finding value with index number

print(myarr[0,0])
print(myarr[0,1])
print(myarr[0,2])
print(myarr[0,3])
print(myarr[0,4])

3
6
9
12


IndexError: index 4 is out of bounds for axis 1 with size 4

In [10]:
print(myarr[1,3])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [11]:
# show the details of array

myarr.shape

(1, 4)

In [12]:
myarray.dtype

dtype('int8')

In [13]:
myarr

array([[ 3,  6,  9, 12]], dtype=int64)

In [14]:
# how to change element in the numpy array

myarr[0,0]=45  #90,50,55
myarr

array([[45,  6,  9, 12]], dtype=int64)

# Note:
 * __There are 5 general mechanism for creating array:__
    * __1. Conversion from other Python structure.(eg:list,tuples)__
    * __2. Instrinsic numpy array Creating object(eg: arange, one, Zeros etc.)__
    * __3. Reading arrays from disk, either from standard or custom formats.__
    * __4. Creating arrays from raw bytes through the use of string of buffers.__
    * __5. Use of special library function eg(random).__

In [21]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [22]:
# Checking the data type of the array

listarray.dtype

dtype('int32')

In [23]:
# Checking the shape of the array.
listarray.shape

(3, 3)

In [24]:
listarray.size

9

In [25]:
# Set array  # Data type object

np.array({34,25,36,88,99},dtype=object)


array({34, 99, 36, 88, 25}, dtype=object)

In [26]:
zero=np.zeros((3,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
zero.dtype

dtype('float64')

In [29]:
range=np.arange(15)

In [30]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
np.linspace(50,50.05,num=100)


array([50.        , 50.00050505, 50.0010101 , 50.00151515, 50.0020202 ,
       50.00252525, 50.0030303 , 50.00353535, 50.0040404 , 50.00454545,
       50.00505051, 50.00555556, 50.00606061, 50.00656566, 50.00707071,
       50.00757576, 50.00808081, 50.00858586, 50.00909091, 50.00959596,
       50.01010101, 50.01060606, 50.01111111, 50.01161616, 50.01212121,
       50.01262626, 50.01313131, 50.01363636, 50.01414141, 50.01464646,
       50.01515152, 50.01565657, 50.01616162, 50.01666667, 50.01717172,
       50.01767677, 50.01818182, 50.01868687, 50.01919192, 50.01969697,
       50.02020202, 50.02070707, 50.02121212, 50.02171717, 50.02222222,
       50.02272727, 50.02323232, 50.02373737, 50.02424242, 50.02474747,
       50.02525253, 50.02575758, 50.02626263, 50.02676768, 50.02727273,
       50.02777778, 50.02828283, 50.02878788, 50.02929293, 50.02979798,
       50.03030303, 50.03080808, 50.03131313, 50.03181818, 50.03232323,
       50.03282828, 50.03333333, 50.03383838, 50.03434343, 50.03

In [42]:
np.linspace(2.0,3.0,num=100, endpoint=False)

array([2.  , 2.01, 2.02, 2.03, 2.04, 2.05, 2.06, 2.07, 2.08, 2.09, 2.1 ,
       2.11, 2.12, 2.13, 2.14, 2.15, 2.16, 2.17, 2.18, 2.19, 2.2 , 2.21,
       2.22, 2.23, 2.24, 2.25, 2.26, 2.27, 2.28, 2.29, 2.3 , 2.31, 2.32,
       2.33, 2.34, 2.35, 2.36, 2.37, 2.38, 2.39, 2.4 , 2.41, 2.42, 2.43,
       2.44, 2.45, 2.46, 2.47, 2.48, 2.49, 2.5 , 2.51, 2.52, 2.53, 2.54,
       2.55, 2.56, 2.57, 2.58, 2.59, 2.6 , 2.61, 2.62, 2.63, 2.64, 2.65,
       2.66, 2.67, 2.68, 2.69, 2.7 , 2.71, 2.72, 2.73, 2.74, 2.75, 2.76,
       2.77, 2.78, 2.79, 2.8 , 2.81, 2.82, 2.83, 2.84, 2.85, 2.86, 2.87,
       2.88, 2.89, 2.9 , 2.91, 2.92, 2.93, 2.94, 2.95, 2.96, 2.97, 2.98,
       2.99])

In [43]:
# empty array

emp=np.empty((4,6))
emp

array([[2.37663529e-312, 2.29175545e-312, 2.33419537e-312,
        2.37663529e-312, 2.10077583e-312, 8.48798317e-313],
       [1.01855798e-312, 1.01855798e-312, 1.06099790e-312,
        9.76118064e-313, 9.33678148e-313, 2.48273508e-312],
       [1.29441743e-312, 1.01855798e-312, 6.79038653e-313,
        2.33419537e-312, 2.37663529e-312, 2.22809558e-312],
       [2.46151512e-312, 1.48539705e-312, 2.29175545e-312,
        2.14321575e-312, 7.40576531e-312, 7.40808937e-312]])

In [47]:
# matrix

b=np.empty(10,dtype=int)
b

array([         0,          0,  341469456,        349,  341470928,
              349,  341471696,        349,  543584032, 1717923683])

In [49]:
print(b)

[         0          0  341469456        349  341470928        349
  341471696        349  543584032 1717923683]


In [52]:
# identity

ide=np.identity(1000)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [53]:
# arange

arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [56]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
arr.shape

(99,)

In [58]:
arr.dtype

dtype('int32')

In [59]:
# numpy array
x=[[1,2,3],[4,5,6],[7,8,0]]
x

[[1, 2, 3], [4, 5, 6], [7, 8, 0]]

In [61]:
x.shape

AttributeError: 'list' object has no attribute 'shape'

In [62]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [63]:
ar.shape

(3, 3)

In [64]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [66]:
ar.sum(axis=0)

array([12, 15,  9])

In [67]:
ar.sum(axis=1)

array([ 6, 15, 15])

In [68]:
a= np.array([1,2,3])
b=a+2
print(b)

[3 4 5]


In [70]:
c=np.array([2,4,6])
d=a+c
print(d)

[3 6 9]


In [71]:
a

array([1, 2, 3])

In [72]:
a1=3*a
a1

array([3, 6, 9])

In [73]:
a

array([1, 2, 3])

In [74]:
a2=a/2
a2

array([0.5, 1. , 1.5])

In [75]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [76]:
c3=ar/2
c3

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 0. ]])

In [77]:
a,b

(array([1, 2, 3]), array([3, 4, 5]))

In [78]:
c4=a*b
c4

array([ 3,  8, 15])

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [80]:
ar.shape

(3, 3)

In [82]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

# Transpose()

 * __With the help of Numpy numpy.transpose(), we can perofrm the simple function of transpose within one line using numpy.transpose() method of numpy. It can transpose the 2-D array on the other hand it has no effect on 1-D arrays. This method transpose the 2-D arrays.__

In [84]:

ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 0]])